### ISSUE TITLE
Typo in SQL Statement

### ISSUE THREAD

**Issue by KristopherKubicki** [KristopherKubicki/glimpser#9]
When I try to update settings on the settings page, I get ta 500 error. The application log states:

```
Traceback (most recent call last):
  File "/home/kristopher/code/glimpser/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kristopher/code/glimpser/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kristopher/code/glimpser/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kristopher/code/glimpser/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/kristopher/code/glimpser/app/routes.py", line 1101, in settings
    update_setting(name, value)
  File "/home/kristopher/code/glimpser/app/routes.py", line 195, in update_setting
    text("SELECT value FROM settings WHERE name = ':name'", {"name": name})
TypeError: text() takes 1 positional argument but 2 were given
```

It looks like we just need to update that SQL statement in app/routes.py.  I suspect there are other messed up queries around there too - can you handle it?

**Comment by KristopherKubicki** [comment]
Fixed 

https://github.com/KristopherKubicki/glimpser/pull/19
